language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t isabellerichard/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true isabellerichard/docker-react npm run test